---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sgbelim/puralsight-spring-cloudconfig-wa-tolls
          search-paths:
            - 'station*'
          #username: uname
          #password: pass